### ISSUE TITLE
Add questions or request here!

### ISSUE THREAD

**Issue by bsy6766** [bsy6766/HeadManager-Wiki#1]

**Comment by jjthomas3** [comment]
I am curious about you intention to maintain this program ? I am willing to host/maintain the Head Manager code base. I previously purchased a copy of it from SpigotMC.org. 

I have decompiled/repaired your code to work on SpigotMC 1.9.4 for my server and am willing to opensource it from my site for other server admins but require your permission.

I would have no intentions of selling it and would make it 100% free code, with credits to you as originating author.

**Comment by jjthomas3** [comment]
I have since updated it to run on SpigotMC 1.10. You are a hard individual to reach. Hopefully you're healthy alive and have simply moved onto newer more exciting things.

**Comment by bsy6766** [comment]
Sorry for late reply and apologize for not maintaining the plugin.

Currently, I have no plan to extend the plugin, so you can update the code to make it work on recent versions. Thanks for kind words and care. 

It's too long story to tell everything here why I stopped working on plugin and what happened.... but again, I apologize for not keeping responsibility, contact, etc.

From now I'll keep look on my github, so feel free to ask anything if you have any questions.

Thanks.
